version: "3.8"

name: note-app-back-end
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm
    volumes:
      - ../..:/workspaces:cached
    # network_mode: service:db
    command: sleep infinity
    networks:
      - my-network

  db:
    image: postgres:16.3-bookworm
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: ../.env
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - 5432:5432
    networks:
      - my-network

  mq:
    image: rabbitmq:3.12-management
    restart: unless-stopped
    # network_mode: service:db
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - my-network

volumes:
  postgres-data:
  rabbitmq-data:

networks:
  my-network:
